---
#
- name: validate oracle weblogic 12c release is supported
  fail: "msg='release is not valid (supported versions: [12.2.1])'"
  when: oracle_weblogic_release is defined and oracle_weblogic_release != '12.2.1'

- name: evaluate oracle weblogic 12c {{ oracle_weblogic_release }} installers
  stat: path="{{ item.path }}"
  register: zips_state
  with_items: "{{ oracle_weblogic_installers_12_2_1_quick }}"
  when: oracle_weblogic_release == '12.2.1'

- name: validation results
  debug:
    var: zips_state

- name: validate installation zips exist
  fail: msg="installation zip file {{ item.item.path }} is not present"
  when: not item.stat.exists or not item.stat.isreg
  with_items: "{{ zips_state.results }}"

- name: validate installation zips checksum
  fail: msg="installation zip file {{ item.item.path }} is not valid"
  when: item.stat.checksum != item.item.checksum
  with_items: "{{ zips_state.results }}"

- name: install the latest version of unzip
  yum: name=unzip state=latest

- set_fact:
    oracle_weblogic_jar: "/tmp/fmw_{{ oracle_weblogic_release }}.0.0_wls_quick.jar"

- name: "unzip installation files"
  unarchive:
    src: "{{ item.path }}"
    dest: /tmp
    creates: "{{ oracle_weblogic_jar }}"
    copy: no
  with_items: "{{ oracle_weblogic_installers_12_2_1_quick }}"
  when: oracle_weblogic_release == '12.2.1'

- name: create group
  group: name={{ oracle_weblogic_os_group }} state=present
- name: create user
  user: name={{ oracle_weblogic_os_user }} group={{ oracle_weblogic_os_group }} state=present

- name: prepare installation directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle_weblogic_os_user }}"
    group: "{{ oracle_weblogic_os_group }}"
  with_items:
    - "{{ oracle_weblogic_oracle_home }}"

- name: install weblogic
  shell: java -jar {{ oracle_weblogic_jar }} ORACLE_HOME={{ oracle_weblogic_oracle_home }}
  args:
    creates: "{{ oracle_weblogic_oracle_home }}/oraInst.loc"
  become: yes
  become_user: "{{ oracle_weblogic_os_user }}"
