---
#
- name: prepare installation response file
  template:
    src: infra-install-12c.rsp.j2
    dest: "{{ oracle_weblogic_infra_response_file }}"
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"

- name: install weblogic infra
  shell: "java -jar {{ oracle_weblogic_infra_jar }} -silent -responseFile {{ oracle_weblogic_infra_response_file }} >> /tmp/infra-installation.log"
  #args:
  #  creates: "{{ oracle_weblogic_oracle_home }}/oraInst.loc"
