---
#
- name: validate oracle weblogic 11g release is supported
  fail: "msg='release is not valid (supported versions: [10.3.6])'"
  when: oracle_weblogic_release != '10.3.6'

- name: create installation directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
  with_items:
    - "{{ oracle_weblogic_oracle_home }}"
    - "{{ oracle_weblogic_inventory_directory }}"

- set_fact:
    oracle_weblogic_response_file: "{{ oracle_weblogic_user_home }}/install-wls-11g.xml"

- name: generate response file
  template:
    source: install-wls-11g.xml.j2
    dest: "{{ oracle_weblogic_response_file }}"

- set_fact:
    oracle_weblogic_install_command: "java -jar {{ oracle_weblogic_jar }} -mode=silent -silent_xml={{ oracle_weblogic_response_file }} >> /tmp/weblogic-installation.log"

- name: install weblogic
  shell: "{{ oracle_weblogic_install_command }}"
  args:
    creates: "{{ oracle_weblogic_oracle_home }}/oraInst.loc"
