---
# tasks file for ansible-oracle-wls
- include: install-wls.yml
  become: yes
  become_user: root
  tags:
    - install_weblogic

- include: install-infra.yml
  when: not oracle_weblogic_quick_installation
  become: yes
  become_user: root
  tags:
    - install_infra
